### ISSUE TITLE
Different assemblies referenced for different platform

### ISSUE THREAD

**Issue by jerriep** [CloudNimble/PortableRest#58]
Hey Robert,

For the Auth0 API client I am adding a reference to the PortableRest Nuget package. This includes a reference to the PortableRest.dll file. 

When I create a Nuget package for the Auth0 API client, I specified that my Nuget package depends on the PortableRest package, so that PortableRest gets installed everytime a user adds a reference to the Auth0 API client Nuget package.

To test this I created a simple .NET4.6 Console application. When I add a reference to the Auth0 Nuget package, the PortablRest package gets installed as expected. This thing is however, that for the .NET 4.6 platform you add a reference not to PortableRest.DLL, but to PortableRest.Universal.DLL

This results in an exception when I try and run my application:

![image](https://cloud.githubusercontent.com/assets/1006420/11418096/2fc1e75c-944f-11e5-99cb-393f56161e95.png)

The core referenced assembly name should surely be the same, regardless of the platform? If they are not I will always run into this issue. Is there a reason why they are not the same?

**Comment by advancedrei** [comment]
Can you please check in your NuGet package for the new Auth0 API into the other repo, so that I can see what you are doing? I think the Auth0 API package needs to reference PortableRest differently on .NET 4.6 to handle how we're compiling the code to support Windows 10. Thanks!

**Comment by jerriep** [comment]
Here you go:
https://github.com/jerriep/auth0.net/tree/FixUpNuget

I do not believe the issue is with how the package is referenced. The problem is that you are producing an assembly with different names under different circumstances. Surely tha actual assembly must always have the same name?

**Comment by jerriep** [comment]
One thing I am curious about though is why it tries and include the Win10 packages? This is was not a UWP application, but a normal Console app...

**Comment by jerriep** [comment]
I am also getting another problem which I seem to have tracked down to PortableRest. 

I create a new Windows Forms application, and add the PortableRest package.

I then add a button on the form and in the button's click handler I create the following code:

```
private async void button1_Click(object sender, EventArgs e)
{
    var restClient = new RestClient();
}
```

As soon as I click on the button, I get the following error:

![image](https://cloud.githubusercontent.com/assets/1006420/11432791/b3d5278c-94e7-11e5-8edd-199860886dd6.png)

Here is the relevant debug output from my application:

```
'WindowsFormsApplication1.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication1.vshost.exe): Loaded 'c:\users\jerriep\documents\visual studio 2015\Projects\WindowsFormsApplication1\WindowsFormsApplication1\bin\Debug\WindowsFormsApplication1.exe'. Symbols loaded.
'WindowsFormsApplication1.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication1.vshost.exe): Loaded 'c:\users\jerriep\documents\visual studio 2015\Projects\WindowsFormsApplication1\WindowsFormsApplication1\bin\Debug\PortableRest.Universal.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
'WindowsFormsApplication1.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

And the exception detail:

```
System.IO.FileNotFoundException was unhandled
  FileName=System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///c:/users/jerriep/documents/visual studio 2015/Projects/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : PortableRest.Universal, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: c:\users\jerriep\documents\visual studio 2015\Projects\WindowsFormsApplication1\WindowsFormsApplication1\bin\Debug\WindowsFormsApplication1.vshost.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.20.0 redirected to 4.0.20.0.
LOG: Post-policy reference: System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///c:/users/jerriep/documents/visual studio 2015/Projects/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/System.Runtime.DLL.
LOG: Attempting download of new URL file:///c:/users/jerriep/documents/visual studio 2015/Projects/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/System.Runtime/System.Runtime.DLL.
LOG: Attempting download of new URL file:///c:/users/jerriep/documents/visual studio 2015/Projects/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/System.Runtime.EXE.
LOG: Attempting download of new URL file:///c:/users/jerriep/documents/visual studio 2015/Projects/WindowsFormsApplication1/WindowsFormsApplication1/bin/Debug/System.Runtime/System.Runtime.EXE.

  HResult=-2147024894
  Message=Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=WindowsFormsApplication1
  StackTrace:
       at WindowsFormsApplication1.Form1.<button1_Click>d__1.MoveNext()
       at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
       at WindowsFormsApplication1.Form1.button1_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at WindowsFormsApplication1.Program.Main() in c:\users\jerriep\documents\visual studio 2015\Projects\WindowsFormsApplication1\WindowsFormsApplication1\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by jerriep** [comment]
BTW, here is the Nuget feed from AppVeyor for the Auth0 project:
https://ci.appveyor.com/nuget/auth0-net-bdq3064hhhbx

**Comment by jerriep** [comment]
@advancedrei Have you had a chance to look at this one?

**Comment by robertmclaws** [comment]
Hey @jerriep sorry I had forgotten about this. You guys aren't using PortableRest in Auth0, are you?

**Comment by jerriep** [comment]
@robertmclaws  Not anymore. No worries, I was just doing GitHub spring cleaning and closing old issues and PRs which are not really relevant anymore.
